ALTER TABLE productos ADD COLUMN IF NOT EXISTS marca VARCHAR(100);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS unidad VARCHAR(20);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS imagen_local VARCHAR(255);
