@echo off
set "UI=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-ui\target\classes"
set "DATA=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-data\target\classes"
set "CORE=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-core\target\classes"
set "SYNC=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-sync\target\classes"
set "FISCAL=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-fiscal\target\classes"
set "PERI=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-peripherals\target\classes"
set "REPO=C:\Users\const\Desktop\productoIntegrador\puntoDeVenta\pos-reports\target\classes"
set "CP=%UI%;%DATA%;%CORE%;%SYNC%;%FISCAL%;%PERI%;%REPO%;C:\Users\const\.m2\repository\org\slf4j\slf4j-api\2.0.12\slf4j-api-2.0.12.jar;C:\Users\const\.m2\repository\ch\qos\logback\logback-classic\1.5.3\logback-classic-1.5.3.jar;C:\Users\const\.m2\repository\ch\qos\logback\logback-core\1.5.3\logback-core-1.5.3.jar;C:\Users\const\.m2\repository\org\postgresql\postgresql\42.7.3\postgresql-42.7.3.jar;C:\Users\const\.m2\repository\org\flywaydb\flyway-core\10.10.0\flyway-core-10.10.0.jar;C:\Users\const\.m2\repository\org\flywaydb\flyway-database-postgresql\10.10.0\flyway-database-postgresql-10.10.0.jar;C:\Users\const\.m2\repository\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;C:\Users\const\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.17.0\jackson-databind-2.17.0.jar;C:\Users\const\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.17.0\jackson-core-2.17.0.jar;C:\Users\const\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.17.0\jackson-annotations-2.17.0.jar;C:\Users\const\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-toml\2.15.2\jackson-dataformat-toml-2.15.2.jar;C:\Users\const\.m2\repository\com\squareup\okhttp3\okhttp\4.12.0\okhttp-4.12.0.jar;C:\Users\const\.m2\repository\com\squareup\okio\okio\3.6.0\okio-3.6.0.jar;C:\Users\const\.m2\repository\com\squareup\okio\okio-jvm\3.6.0\okio-jvm-3.6.0.jar;C:\Users\const\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.8.21\kotlin-stdlib-1.8.21.jar;C:\Users\const\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.8.21\kotlin-stdlib-jdk7-1.8.21.jar;C:\Users\const\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.8.21\kotlin-stdlib-jdk8-1.8.21.jar"
set "MP=C:\Users\const\.m2\repository\org\openjfx\javafx-base\21.0.1\javafx-base-21.0.1-win.jar;C:\Users\const\.m2\repository\org\openjfx\javafx-controls\21.0.1\javafx-controls-21.0.1-win.jar;C:\Users\const\.m2\repository\org\openjfx\javafx-fxml\21.0.1\javafx-fxml-21.0.1-win.jar;C:\Users\const\.m2\repository\org\openjfx\javafx-graphics\21.0.1\javafx-graphics-21.0.1-win.jar"
java --enable-native-access=javafx.graphics --module-path "%MP%" --add-modules javafx.controls,javafx.fxml -cp "%CP%" com.empresa.pos.ui.Launcher
